name: win32_registry
description: A package that provides a friendly Dart API for accessing the
  Windows Registry.
version: 2.0.1
repository: https://github.com/halildurmus/win32_registry
issue_tracker: https://github.com/halildurmus/win32_registry/issues

topics:
  - registry
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.5.0

platforms:
  windows:

dependencies:
  ffi: ^2.1.3
  meta: ^1.16.0
  win32: ^5.8.0

dev_dependencies:
  checks: ^0.3.0
  hooks:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/hooks
  lints:
    git:
      url: https://github.com/halildurmus/workflows.git
      path: packages/lints
  test: ^1.25.8
