name: win32_registry
description: A package that provides a friendly Dart API for accessing the
  Windows Registry.
version: 1.1.5
repository: https://github.com/halildurmus/win32_registry
issue_tracker: https://github.com/halildurmus/win32_registry/issues

topics:
  - registry
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.4.0

platforms:
  windows:

dependencies:
  ffi: ^2.1.3
  win32: ^5.5.4

dev_dependencies:
  checks: ^0.3.0
  lints: ^4.0.0
  test: ^1.25.8
